// generated by stringer -type=GroupAdminLevel; DO NOT EDIT

package vk

import "fmt"

const _GroupAdminLevel_name = "GroupModeratorGroupRedactorGroupAdministrator"

var _GroupAdminLevel_index = [...]uint8{0, 14, 27, 45}

func (i GroupAdminLevel) String() string {
	i -= 1
	if i < 0 || i+1 >= GroupAdminLevel(len(_GroupAdminLevel_index)) {
		return fmt.Sprintf("GroupAdminLevel(%d)", i+1)
	}
	return _GroupAdminLevel_name[_GroupAdminLevel_index[i]:_GroupAdminLevel_index[i+1]]
}
