// generated by stringer -type=Relation; DO NOT EDIT

package vk

import "fmt"

const _Relation_name = "RelationUnknownRelationSingleRelationHasFriendRelationEngagedRelationMarriedRelationComplicatedRelationActiveSearchRelationInLove"

var _Relation_index = [...]uint8{0, 15, 29, 46, 61, 76, 95, 115, 129}

func (i Relation) String() string {
	if i < 0 || i+1 >= Relation(len(_Relation_index)) {
		return fmt.Sprintf("Relation(%d)", i)
	}
	return _Relation_name[_Relation_index[i]:_Relation_index[i+1]]
}
